HELP = {
    "Erkennungsprofil": "Schnell: YOLO11n bei 640 px, ein Durchlauf und Skeleton aus. Ausgewogen: YOLO11s-Pose bei 640 px. Qualität: YOLO11m-Pose bei 1536 px mit fünf Durchläufen, deutlich langsamer. Profilwechsel nur bei gestoppter Sitzung. Schnellere Profile können kleine Figuren übersehen.",
    "Teilbild-Erkennung für kleine Figuren": "Analysiert zusätzlich zum Vollbild vier überlappende Ausschnitte aus demselben Screenshot. Erhält mehr Details kleiner Figuren und entfernt doppelte Boxen. Bis zu fünf Inferenzdurchläufe; deutlich langsamer, besonders ohne CUDA.",
    "Gesamten Bildschirm zur Auswahl verwenden": "Entfernt das Radiuslimit für die Zielauswahl. Die Erkennung selbst umfasst immer den gesamten Bildschirm. Der Eigenfigur-Filter bleibt aktiv.",
    "Unsichere Kandidaten unter": "Boxen unter diesem Konfidenzwert erhalten die Kandidatenfarbe und gestrichelte Rahmen. Eine hohe Konfidenz beweist trotzdem nicht, dass es ein Spieler ist.",
    "Linien-ESP": "Zeichnet eine Linie vom gewählten Bildschirmursprung zum unteren Mittelpunkt jeder sichtbaren Erkennung.",
    "Skeleton-ESP": "Standardmäßig aus für weniger Latenz. Offizielle Pose-Modelle liefern Gelenke direkt. Detect-Modelle benötigen einen zusätzlichen YOLO11n-Pose-Durchlauf bei 640 px, der die Erkennung verlangsamt. Fehlende Gelenke werden nicht erfunden.",
    "Gelenkpunkte anzeigen": "Markiert Endpunkte der ausreichend sicher erkannten Skelettverbindungen. Nur bei aktivem Skeleton-ESP sichtbar.",
    "Zielpunkt anzeigen": "Zeigt den berechneten Auswahlpunkt als kleinen weißen Kreis. Dieser Punkt ist keine anatomische Messung.",
    "Rahmenstil": "Wähle vollständige Rechtecke oder kompakte Eckrahmen.",
    "Linienursprung": "Startpunkt der ESP-Linien: unten, oben oder Bildschirmmitte.",
    "Linienstärke": "Breite von Rahmen, Linien und Skeletten in Bildschirm-Pixeln.",
    "ESP-Deckkraft": "Gemeinsame Deckkraft der Erkennungsanzeige. Die Eigenzonen-Bearbeitung bleibt gut sichtbar.",
    "Rahmenfüllung": "Transparente Füllung innerhalb der Boxen. 0 schaltet die Füllung aus.",
    "Gelenk-Konfidenz": "Beide Gelenke einer Verbindung müssen diesen Wert erreichen. Höhere Werte reduzieren falsch gezeichnete Knochen, können aber Teile des Skeletts ausblenden.",
    "Rahmenfarbe": "Farbe der Rahmen oberhalb der Kandidatenschwelle.",
    "Kandidatenfarbe": "Farbe für unsichere, mögliche Personen.",
    "Linienfarbe": "Farbe der Verbindungen vom Bildschirmursprung zu den erkannten Figuren.",
    "Skelettfarbe": "Farbe der erkannten Gelenkverbindungen.",
    "Eigenzone bearbeiten / Vorschau": "Zeigt die Eigenzone ausschließlich auf dem Eigenfigur-Tab, solange dieses Einstellungsfenster im Vordergrund ist. Funktioniert auch vor einer Sitzung. Ausgeschaltet bleibt die Zone unsichtbar; der Ausschlussfilter arbeitet unabhängig davon.",
    "Game display (crosshair must be centered)": "Wähle den Bildschirm mit dem Spiel. Das Fadenkreuz muss in dessen Mitte liegen; empfohlen ist randloses Vollbild.",
    "Required foreground window title contains": "Mauseingaben erfolgen nur, wenn dieser Text im Titel des aktiven Spielfensters vorkommt. Außerhalb des Spiels bleibt die Eingabe gesperrt.",
    "Detection model": "Das allgemeine Modell erkennt Personen, nicht zuverlässig Retrac-Gegner. Für bessere Ergebnisse ein auf Retrac trainiertes, vertrauenswürdiges Modell laden.",
    "Target class ID (starter: 0 = person)": "Automatisch (-1) sucht person, player oder enemy und vermeidet head-Boxen. Bei eigenen Klassennamen eine konkrete ID angeben; unbekannte Klassen werden nicht stillschweigend als Spieler verwendet. Personenmodelle unterscheiden nicht zwischen Gegnern und Teammitgliedern.",
    "Hold-to-aim hotkey": "Klicken und eine Taste oder Maustaste drücken. Escape bricht ab; F8 bleibt Notstopp. Änderungen nur bei gestoppter Sitzung.",
    "Pause / resume hotkey": "Pausiert oder startet Erkennung und Zielbewegung innerhalb der Sitzung. F8 beendet die Sitzung unabhängig davon.",
    "Smoothness · 0 = direkt": "0 bewegt direkt zum zuletzt erkannten Ziel, sofern kein Bewegungslimit gesetzt ist. Höhere Werte glätten zeitbasiert; die Eingabeschleife läuft unabhängig von der KI mit bis zu 240 Abfragen pro Sekunde. Windows und Hardware bestimmen die tatsächliche Rate. Mehr als 250 ms alte Bilder lösen keine Bewegung aus.",
    "Eingabemodus": "Cursor bewegt den sichtbaren Windows-Zeiger von seiner echten Position zum Ziel und berücksichtigt Monitorversatz. Fadenkreuz sendet relative Bewegung ab Bildschirmmitte; das Spiel muss sie akzeptieren. Sensitivität und Raw Input verhindern eine garantierte pixelgenaue Kamerabewegung. Keine Umgehung von Eingabesperren.",
    "Aim point · % from top of detected box": "Relative Höhe innerhalb der erkannten Personenbox: 0 ist oben, 100 unten. Dies ist keine anatomische Kopf- oder Gelenkerkennung.",
    "Bewegungslimit · 0 = unbegrenzt": "0 entfernt das zusätzliche Tempolimit. Andere Werte begrenzen die Bewegung zeitbasiert auf Wert × 60 Pixel pro Sekunde, unabhängig von der Erkennungsrate. Smoothness arbeitet zusätzlich. Im Fadenkreuz-Modus wird derselbe Bildversatz nicht wiederholt aufsummiert.",
    "Minimum confidence": "Kleinere Werte lassen unsichere Erkennungen zu und können kleine Ziele finden, erhöhen aber Fehlalarme. Keine Garantie für mehr Reichweite.",
    "Target selection radius": "Radius um die Bildschirmmitte in Pixeln. Erweitert nur die Zielauswahl, nicht die Fähigkeit des Modells, weit entfernte Personen zu erkennen.",
    "Erkennungsauflösung": "Standard: 640 px. 320 oder 416 px reduzieren Rechenlast weiter, können aber kleine Figuren übersehen. 960 bis 1536 px und Teilbilder erhöhen die Last stark. Bildalter und Inferenz-FPS werden angezeigt; es gibt keine garantierte Reichweite oder FPS.",
    "Zielbereich": "Kopf, Körper und Becken sind Näherungen relativ zur Personenbox, keine erkannten Körperteile. Es werden keine Schüsse ausgelöst.",
    "Detect across desktop · game focus not required": "Erkennung läuft auch außerhalb des Spiels. Mauseingaben bleiben auf das konfigurierte Spielfenster beschränkt.",
    "Enable mouse input": "Standardmäßig freigegeben, jedoch nur während einer gestarteten Sitzung, bei passendem Spielfokus, frischem Ziel und gehaltenem Ziel-Hotkey. Ausschalten für reine Erkennung. Die Option bleibt beim Sitzungswechsel erhalten; ohne laufende Sitzung findet keine Eingabe statt. Der separate Automatikmodus kann den gehaltenen Hotkey ersetzen.",
    "Automatisch zielen ohne gehaltenen Hotkey": "Nach Freigabe der Mauseingabe wird im aktiven Spielfenster ohne gehaltenen Hotkey gezielt. Kein automatisches Schießen. F8 beendet die Sitzung.",
    "Eigenfigur-Ausschlusszone aktiv": "Verwirft Personenboxen, deren Mittelpunkt in der orangefarbenen Zone liegt. Das ist ein räumlicher Filter, keine Identitätserkennung; auch Gegner in dieser Zone werden ausgeschlossen.",
    "Links": "Linke Grenze der Ausschlusszone in Prozent der Bildschirmbreite. Passe die Zone an die Position deiner eigenen Figur an.",
    "Rechts": "Rechte Grenze der Ausschlusszone in Prozent der Bildschirmbreite. Muss größer als Links sein.",
    "Oben": "Obere Grenze der Ausschlusszone in Prozent der Bildschirmhöhe. Muss kleiner als Unten sein.",
    "Unten": "Untere Grenze der Ausschlusszone in Prozent der Bildschirmhöhe.",
    "Show visible-target bounding boxes": "Zeigt die nach dem Ausschlussfilter verbleibenden sichtbaren Personen. Keine Sicht durch Wände.",
    "Show class and confidence": "Zeigt Modellklasse und Konfidenz. Konfidenz ist keine Garantie für eine korrekte Gegnererkennung.",
    "Show selection radius": "Zeigt den Kreis, innerhalb dessen das nächstgelegene Ziel ausgewählt wird.",
    "Test selected display capture": "Erstellt einen lokalen Screenshot des gewählten Bildschirms ohne KI-Modell, um die Bildschirmaufnahme zu prüfen.",
    "Choose trusted .pt model": "Lädt ein eigenes Modell. Nur vertrauenswürdige Dateien verwenden: PyTorch-Dateien können Code ausführen.",
    "Use starter": "Setzt das schnelle Standardprofil mit YOLO11n, 640 px, einem Durchlauf und Skeleton aus zurück. Gewichte werden einmal heruntergeladen. Das zuletzt verwendete Modell bleibt für weitere Sitzungen im Arbeitsspeicher.",
    "Start session": "Startet Aufnahme und Erkennung. Standardmäßig bewegt der gehaltene Ziel-Hotkey den Cursor zum erkannten Ziel im fokussierten Spielfenster. F8 beendet die Sitzung.",
    "Stop · F8": "Stoppt weitere Mauseingaben ohne auf die nächste Erkennung zu warten. Eine bereits laufende Modelloperation oder ein Download muss noch enden, bevor die Sitzung vollständig geschlossen wird.",
}
